Updated AutoCompletions
aviaryan/lc3-sublime pull request #3
Opened 2017-03-30 20:35 UTC by Monal5031

Added AutoCompletion in rest of the instructions.
Have tested it my local system too.

2017-03-30 20:37 UTC, aviaryan requested changes
Please see the comments.

2017-03-30 20:37 UTC, aviaryan commented on LC3-ASM.sublime-completions
> +            { "trigger": "LDR", "contents": "LDR ${1:Dest}, ${2:Src}, ${3:x(OffSet)}"},
Please make OffSet as `Offset` as it is a valid English word.

2017-03-30 20:37 UTC, aviaryan commented on LC3-ASM.sublime-completions
> +            { "trigger": "ST", "contents": "ST ${1:Src}, ${2:LABEL}"},
Make `LABEL` as `Label` to be consistent with the rest.

2017-03-30 20:37 UTC, aviaryan commented on LC3-ASM.sublime-completions
> +            { "trigger": ".ORIG", "contents": ".ORIG xStart-Address"}
Missing a `{...}` here.

2017-03-30 20:48 UTC, Monal5031 commented on LC3-ASM.sublime-completions
> +            { "trigger": ".ORIG", "contents": ".ORIG xStart-Address"}
Sorry didn't get this one.

2017-03-30 20:49 UTC, aviaryan commented on LC3-ASM.sublime-completions
> +            { "trigger": ".ORIG", "contents": ".ORIG xStart-Address"}
Is this correct? `.ORIG xStart-Address`

2017-03-30 20:51 UTC, Monal5031 commented on LC3-ASM.sublime-completions
> +            { "trigger": ".ORIG", "contents": ".ORIG xStart-Address"}
Yes, we generally write it as `.ORIG x3000`

2017-03-31 20:24 UTC, Monal5031 commented
@aviaryan Please review this one so that I can add the test code too.

2017-03-31 20:32 UTC, aviaryan approved these changes
LGTM

2017-03-31 20:32 UTC, merged